language: r
compiler: gcc

sudo: required
cache: packages

before_script:
  - bash travis.sh

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libstdc++-7-dev

notifications:
  email:
    on_success: always
    on_failure: always

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'