language: r

include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="export CC=gcc-6"

before_script:
  - bash travis.sh

sudo: required

cache: packages

notifications:
  email:
    on_success: always
    on_failure: always

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'