language: r
compiler: gcc

sudo: required
cache: packages

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libstdc++-7-dev

before_script:
  - export CC=gcc-7
  - export CXX=g++17
  - export CXX_STD=g++17
  - export LD=-std=gnu++17
  - bash travis.sh

notifications:
  email:
    on_success: always
    on_failure: always

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'