language: r

include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - libstdc++-7-dev
          - libpng-dev
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - LINKER_FLAGS="-std=gnu++17"

before_script:
  - bash travis.sh

sudo: required

cache: packages

notifications:
  email:
    on_success: always
    on_failure: always

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'