language: r

before_script:
  - travis.sh

sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'