// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_binseg
Rcpp::NumericMatrix rcpp_binseg(Rcpp::NumericVector data, Rcpp::String algorithm, Rcpp::String distribution, int numCpts, int minSegLen);
RcppExport SEXP _BinSeg_rcpp_binseg(SEXP dataSEXP, SEXP algorithmSEXP, SEXP distributionSEXP, SEXP numCptsSEXP, SEXP minSegLenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type algorithm(algorithmSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type distribution(distributionSEXP);
    Rcpp::traits::input_parameter< int >::type numCpts(numCptsSEXP);
    Rcpp::traits::input_parameter< int >::type minSegLen(minSegLenSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_binseg(data, algorithm, distribution, numCpts, minSegLen));
    return rcpp_result_gen;
END_RCPP
}
// distributions_info
Rcpp::CharacterMatrix distributions_info();
RcppExport SEXP _BinSeg_distributions_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(distributions_info());
    return rcpp_result_gen;
END_RCPP
}
// algorithms_info
Rcpp::CharacterMatrix algorithms_info();
RcppExport SEXP _BinSeg_algorithms_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(algorithms_info());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BinSeg_rcpp_binseg", (DL_FUNC) &_BinSeg_rcpp_binseg, 5},
    {"_BinSeg_distributions_info", (DL_FUNC) &_BinSeg_distributions_info, 0},
    {"_BinSeg_algorithms_info", (DL_FUNC) &_BinSeg_algorithms_info, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BinSeg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
