# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_binseg <- function(data, algorithm, distribution, numCpts, minSegLen) {
    .Call(`_BinSeg_rcpp_binseg`, data, algorithm, distribution, numCpts, minSegLen)
}

distributions_info <- function() {
    .Call(`_BinSeg_distributions_info`)
}

algorithms_info <- function() {
    .Call(`_BinSeg_algorithms_info`)
}

