# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binseg <- function(data, algorithm, distribution, numCpts, minSegLen = 1L) {
    .Call(`_BinSeg_binseg`, data, algorithm, distribution, numCpts, minSegLen)
}

